# Site settings
title: anditriathlon
email: andi@anditriathlon.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for sharing my passion for triathlon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anditriathlon.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: ""